export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const MESSAGE_RECEIVED_PARENT = "MESSAGE_RECEIVED_PARENT";
export const FEATCHING = "FEATCHING";
export const FEATCHING_MESSAGES = "FEATCHING_MESSAGES";
//syndic
export const MESSAGE_SYNDIC_RECEIVED = "MESSAGE_SYNDIC_RECEIVED";
export const MESSAGE_SYNDIC_RECEIVED_PARENT = "MESSAGE_SYNDIC_RECEIVED_PARENT";
export const FEATCHING_SYNDIC = "FEATCHING_SYNDIC";
export const FEATCHING_SYNDIC_MESSAGES = "FEATCHING_MESSAGES";